replicaCount: 1

fullname: portfolio

image:
  repository: wikimax/portfolio
  tag: latest
  pullPolicy: Always

service:
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: toastcie.dev
